# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libros',
            name='sinopsis',
            field=models.CharField(default='', max_length=400),
        ),
    ]
