# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-25 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Libros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=50)),
                ('portada', models.ImageField(upload_to='imagenes/portada')),
                ('sinopsis', models.CharField(default='', max_length=200)),
                ('genero', models.ManyToManyField(to='booker.Genero')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('contrasenya', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='libros',
            name='usuario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='booker.Usuarios'),
        ),
    ]
