# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0003_auto_20170503_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='libros',
            name='contenido',
            field=models.FileField(default='', upload_to='booker/libros'),
        ),
    ]
